[package]
name = "recipes_api"
version = "0.0.1"
authors = ["Daniel Sauv√© <daniel@xn--sauv-epa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["sqlite"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4.4"
rocket_okapi = "0.4.1"
schemars = "0.7.1"
okapi = { version = "0.4.0", features = ["derive_json_schema"] }


[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["json"]